### ISSUE TITLE
AggregateNotFoundException: No 'given' events were configured for this aggregate, nor have any events been stored.

### ISSUE THREAD

**Issue by tullo** [dilgerma/eventsourcing-book#8]
When running the tests on the `main` branch with `./mvnw test` in a gitpod instance I get the following right in the beginning:

```text
[INFO] --- kotlin:2.0.0:test-compile (test-compile) @ cart ---
[INFO] Applied plugin: 'spring'
[INFO] Applied plugin: 'jpa'
[INFO] Applied plugin: 'no-arg'
[WARNING] /workspaces/eventsourcing-book/src/test/kotlin/de/eventsourcingbook/cart/cartitems/integration/CartItemsUpcasterTest.kt: (12, 8) '@Deprecated(...) data class ItemAddedEvent : Event' is deprecated. V2.
[WARNING] /workspaces/eventsourcing-book/src/test/kotlin/de/eventsourcingbook/cart/cartitems/integration/CartItemsUpcasterTest.kt: (49, 44) '@Deprecated(...) data class ItemAddedEvent : Event' is deprecated. V2.
[INFO] 
[INFO] --- surefire:3.2.5:test (default-test) @ cart ---
[INFO] Using auto detected provider org.apache.maven.surefire.junitplatform.JUnitPlatformProvider
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running de.eventsourcingbook.cart.submitcart.SubmitcartAggregateTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.593 s -- in de.eventsourcingbook.cart.submitcart.SubmitcartAggregateTest
[INFO] Running de.eventsourcingbook.cart.submitcart.SubmitemptycartAggregateTest
13:01:45.946 [main] WARN org.axonframework.modelling.command.AbstractRepository -- Exception occurred while trying to load a aggregate with identifier [81dc9829-f6ff-4a80-a8c2-b70e021c0330].
org.axonframework.modelling.command.AggregateNotFoundException: No 'given' events were configured for this aggregate, nor have any events been stored.
	at org.axonframework.test.aggregate.AggregateTestFixture$RecordingEventStore.readEvents(AggregateTestFixture.java:993)
	at org.axonframework.eventsourcing.EventSourcingRepository.readEvents(EventSourcingRepository.java:171)
	at org.axonframework.eventsourcing.EventSourcingRepository.doLoadWithLock(EventSourcingRepository.java:131)
	at org.axonframework.eventsourcing.EventSourcingRepository.doLoadWithLock(EventSourcingRepository.java:56)
...
```

I'm a bit surprised that the exception only is logged at warn level at does not abort execution of further tests.

**Comment by dilgerma** [comment]
Works for me. Is it possible you do not have docker available? The integration tests require docker - error message would be exactly this.

**Comment by tullo** [comment]
It is not about anything not working. All the test run through. Apparently it is the axon framework that decides to log the exception as a warning.

And the test outcome is succesful b/c of the `.expectException(AggregateNotFoundException::class.java)` 

`[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.111 s -- in de.eventsourcingbook.cart.submitcart.SubmitemptycartAggregateTest`

**Comment by dilgerma** [comment]
I see, that is possible if the command was not processed and the first test iteration is already starting.
